sudo: false
language: node_js
cache: yarn
notifications:
  email: false
install: yarn install
script: yarn run validate
after_success: kcd-scripts travis-after-success
after_failure: kcd-scripts travis-after-success
branches:
  only: master
